# Generated by Django 6.0.3 on 2026-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.TextField(blank=True, verbose_name='URL de checkout'),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_event',
            field=models.JSONField(blank=True, default=dict, verbose_name='Evento proveedor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Checkout Session'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email cliente Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe PaymentIntent'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(max_length=80, unique=True, verbose_name='Pedido / referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('redsys', 'Redsys'), ('stripe', 'Stripe')], default='redsys', max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Devuelto'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
