# Generated by Django 6.0.3 on 2026-06-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_url_payment_raw_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe devuelto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo devolución'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devuelto el'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Refund'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('redsys', 'Redsys'), ('stripe', 'Stripe')], default='redsys', max_length=30, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partially_paid', 'Parcialmente pagado'), ('extra_payment_pending', 'Pago extra pendiente'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Devuelto'), ('partially_refunded', 'Parcialmente devuelto'), ('refund_pending', 'Devolución pendiente'), ('expired', 'Expirado')], default='pending', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('refunded', 'Devuelta'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Refund')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Devuelto el')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Devolución online',
                'verbose_name_plural': 'Devoluciones online',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
