# Generated by Django 5.2.14 on 2026-08-13 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_amount_refunded_payment_refund_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('method', models.CharField(choices=[('standard', 'Estándar'), ('instant', 'Instantánea')], max_length=20)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='processing', max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
