# Generated by Django 6.0.3 on 2026-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('services_app', '0002_service_allowed_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='services_app.service', verbose_name='Servicios que realiza'),
        ),
    ]
