# Generated by Django 6.0.3 on 2026-04-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
    ]
