# Generated by Django 6.0.3 on 2026-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Porcentaje del empleado'),
        ),
    ]
