# Generated by Django 6.0.3 on 2026-04-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_schedule_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Inicio')),
                ('end_time', models.TimeField(verbose_name='Fin')),
                ('label', models.CharField(blank=True, max_length=140, verbose_name='Motivo')),
                ('color', models.CharField(default='#111111', max_length=20, verbose_name='Color')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Bloqueo horario',
                'verbose_name_plural': 'Bloqueos horarios',
                'ordering': ['employee', 'date', 'start_time', 'end_time', 'pk'],
            },
        ),
    ]
