# Generated by Django 6.0.3 on 2026-05-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_break_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecurringTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Inicio')),
                ('end_time', models.TimeField(verbose_name='Fin')),
                ('label', models.CharField(blank=True, max_length=140, verbose_name='Motivo')),
                ('color', models.CharField(default='#111111', max_length=20, verbose_name='Color')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_time_blocks', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Bloqueo horario recurrente',
                'verbose_name_plural': 'Bloqueos horarios recurrentes',
                'ordering': ['employee', 'weekday', 'start_time', 'end_time', 'pk'],
            },
        ),
    ]
