# Generated by Django 5.2.14 on 2026-07-30 21:09

from django.db import migrations, models


def assign_existing_zones(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    Zone = apps.get_model("salon", "Zone")
    zone_ids = list(Zone.objects.filter(is_active=True).values_list("pk", flat=True))
    for employee in Employee.objects.all():
        employee.zones.add(*zone_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerecurringtimeblock'),
        ('salon', '0003_salonsettings_receipt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='employees', to='salon.zone', verbose_name='Zonas en las que trabaja'),
        ),
        migrations.RunPython(assign_existing_zones, migrations.RunPython.noop),
    ]
