# Generated by Django 5.2.14 on 2026-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_vacation_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescheduleoverride',
            name='is_vacation',
            field=models.BooleanField(default=False, verbose_name='Vacaciones'),
        ),
    ]
