# Generated by Django 6.0.3 on 2026-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('zone_type', models.CharField(choices=[('cabin', 'Cabina'), ('table', 'Mesa'), ('wash', 'Lavacabezas'), ('makeup', 'Maquillaje'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Tipo')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Capacidad')),
                ('color', models.CharField(default='#e291b3', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['name'],
            },
        ),
    ]
