# Generated by Django 5.2.14 on 2026-08-14 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_salonsettings_receipt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_minimum_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe mínimo de prepago'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_rounding',
            field=models.CharField(choices=[('none', 'Sin redondeo'), ('up_to_euro', 'Redondear hacia arriba al euro')], default='up_to_euro', max_length=20, verbose_name='Redondeo del prepago'),
        ),
    ]
