# Generated by Django 6.0.3 on 2026-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Titulo')),
                ('instagram_url', models.URLField(verbose_name='URL de Instagram')),
                ('embed_html', models.TextField(blank=True, verbose_name='Embed blockquote')),
                ('caption', models.TextField(blank=True, verbose_name='Texto')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Post de Instagram',
                'verbose_name_plural': 'Posts de Instagram',
                'ordering': ['sort_order', '-created_at', '-id'],
            },
        ),
    ]
