# Generated by Django 6.0.3 on 2026-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='ID de media Instagram'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo de media'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL de media'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado en Instagram'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='synced_from_api',
            field=models.BooleanField(default=False, verbose_name='Sincronizado por API'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL de miniatura'),
        ),
    ]
