# Generated by Django 6.0.3 on 2026-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_instagrampost_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_url',
            field=models.URLField(max_length=2000, verbose_name='URL de Instagram'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.TextField(blank=True, verbose_name='URL de media'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.TextField(blank=True, verbose_name='URL de miniatura'),
        ),
    ]
