# Generated by Django 6.0.3 on 2026-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_instagrampost_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='cached_media',
            field=models.FileField(blank=True, upload_to='instagram_cache/%Y/%m/', verbose_name='Media en cache'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='cached_thumbnail',
            field=models.FileField(blank=True, upload_to='instagram_cache/%Y/%m/', verbose_name='Miniatura en cache'),
        ),
    ]
