CLIENT_LANGUAGES = [
    ("es", "Español"),
    ("ru", "Русский"),
    ("en", "English"),
    ("de", "Deutsch"),
    ("fr", "Français"),
]

DEFAULT_CLIENT_LANGUAGE = "es"
CLIENT_LANGUAGE_SESSION_KEY = "client_language"

CLIENT_TRANSLATIONS = {
    "es": {
        "portal_client": "Portal cliente", "site_home": "Sitio", "logout": "Salir", "my_portal": "Mi portal", "my_data": "Mis datos", "hello": "Hola, {name}",
        "portal_subtitle": "Tu historial, fotos autorizadas, premios y nueva solicitud de reserva.", "my_file": "Mi ficha", "no_phone": "Sin telefono", "no_email": "Sin email", "my_avatar": "Mi avatar", "update_avatar": "Actualizar avatar", "visits": "Visitas", "rewards": "Premios", "upcoming_bookings": "Proximas citas", "no_upcoming_bookings": "Todavia no tienes proximas citas.", "rewards_help": "Pulsa una recompensa en la app al reservar. Aqui puedes ver cuanto falta y que descuento tiene cada una.", "discount": "Descuento", "need_now": "Necesitas {threshold}; ahora tienes {current}.", "available": "Disponible:", "missing": "Faltan:", "completed": "Completado.", "no_rewards": "No hay premios activos.", "new_booking_request": "Nueva solicitud de reserva", "booking_help": "Elige servicio, fecha, hora y master. La solicitud queda pendiente hasta que el salon la confirme.", "service": "Servicio", "date": "Fecha", "available_time": "Hora disponible", "select_service_date": "Selecciona servicio y fecha", "master": "Master", "zone": "Zona", "reward": "Premio", "comment": "Comentario", "send_request": "Enviar solicitud", "visual_history": "Historial visual", "no_visible_photos": "Todavia no hay fotos visibles para ti.", "booking_history": "Historial de reservas", "no_bookings": "Todavia no tienes reservas.", "select_master": "Elige master", "next_short": "prox. {time}", "no_free_time": "sin horario libre", "no_free_hours": "No hay horas libres", "no_availability_for_service_date": "No hay horarios disponibles para este servicio y fecha.", "choose_time": "Elige una hora", "masters_count": "{count} master{suffix}", "choose_time_master": "Elige una hora y despues un master disponible.", "searching_availability": "Buscando horarios disponibles...", "availability_load_error": "No se pudo cargar disponibilidad.", "time_available_submit": "Horario disponible. Puedes enviar la solicitud.", "profile_subtitle": "Actualiza tus datos de usuario, contacto y contrasena.", "username": "Usuario", "first_name": "Nombre", "last_name": "Apellidos", "email": "Email", "phone": "Telefono", "save_data": "Guardar datos", "back": "Volver", "change_password": "Cambiar contrasena", "change_password_help": "Actualiza tu acceso al portal con una nueva contrasena.", "current_password": "Contrasena actual", "new_password": "Nueva contrasena", "repeat_password": "Repetir contrasena", "save_password": "Guardar password",
    },
    "ru": {
        "portal_client": "Клиентский портал", "site_home": "На сайт", "logout": "Выйти", "my_portal": "Мой портал", "my_data": "Мои данные", "hello": "Здравствуйте, {name}",
        "portal_subtitle": "Ваша история, доступные фото, бонусы и новая заявка на запись.", "my_file": "Моя анкета", "no_phone": "Телефон не указан", "no_email": "Email не указан", "my_avatar": "Мой аватар", "update_avatar": "Обновить аватар", "visits": "Визиты", "rewards": "Бонусы", "upcoming_bookings": "Ближайшие записи", "no_upcoming_bookings": "У вас пока нет ближайших записей.", "rewards_help": "Выберите бонус при записи. Здесь видно, сколько осталось и какая скидка действует.", "discount": "Скидка", "need_now": "Нужно {threshold}; сейчас у вас {current}.", "available": "Доступно:", "missing": "Осталось:", "completed": "Выполнено.", "no_rewards": "Активных бонусов нет.", "new_booking_request": "Новая заявка на запись", "booking_help": "Выберите услугу, дату, время и мастера. Заявка будет ожидать подтверждения салона.", "service": "Услуга", "date": "Дата", "available_time": "Доступное время", "select_service_date": "Выберите услугу и дату", "master": "Мастер", "zone": "Зона", "reward": "Бонус", "comment": "Комментарий", "send_request": "Отправить заявку", "visual_history": "Фотоистория", "no_visible_photos": "Пока нет доступных вам фото.", "booking_history": "История записей", "no_bookings": "У вас пока нет записей.", "select_master": "Выберите мастера", "next_short": "ближ. {time}", "no_free_time": "нет свободного времени", "no_free_hours": "Нет свободного времени", "no_availability_for_service_date": "Нет доступного времени для этой услуги и даты.", "choose_time": "Выберите время", "masters_count": "мастеров: {count}", "choose_time_master": "Выберите время, затем доступного мастера.", "searching_availability": "Ищем доступное время...", "availability_load_error": "Не удалось загрузить доступное время.", "time_available_submit": "Время доступно. Можно отправить заявку.", "profile_subtitle": "Обновите данные пользователя, контакты и пароль.", "username": "Логин", "first_name": "Имя", "last_name": "Фамилия", "email": "Email", "phone": "Телефон", "save_data": "Сохранить данные", "back": "Назад", "change_password": "Сменить пароль", "change_password_help": "Обновите пароль для входа в портал.", "current_password": "Текущий пароль", "new_password": "Новый пароль", "repeat_password": "Повторите пароль", "save_password": "Сохранить пароль",
    },
    "en": {
        "portal_client": "Client portal", "site_home": "Website", "logout": "Log out", "my_portal": "My portal", "my_data": "My details", "hello": "Hello, {name}",
        "portal_subtitle": "Your history, approved photos, rewards and a new booking request.", "my_file": "My profile", "no_phone": "No phone", "no_email": "No email", "my_avatar": "My avatar", "update_avatar": "Update avatar", "visits": "Visits", "rewards": "Rewards", "upcoming_bookings": "Upcoming bookings", "no_upcoming_bookings": "You do not have upcoming bookings yet.", "rewards_help": "Choose a reward when booking. Here you can see what is left and the discount.", "discount": "Discount", "need_now": "You need {threshold}; now you have {current}.", "available": "Available:", "missing": "Missing:", "completed": "Completed.", "no_rewards": "No active rewards.", "new_booking_request": "New booking request", "booking_help": "Choose service, date, time and master. The request stays pending until the salon confirms it.", "service": "Service", "date": "Date", "available_time": "Available time", "select_service_date": "Select service and date", "master": "Master", "zone": "Zone", "reward": "Reward", "comment": "Comment", "send_request": "Send request", "visual_history": "Photo history", "no_visible_photos": "No photos visible to you yet.", "booking_history": "Booking history", "no_bookings": "You do not have bookings yet.", "select_master": "Choose master", "next_short": "next {time}", "no_free_time": "no free time", "no_free_hours": "No free times", "no_availability_for_service_date": "No available times for this service and date.", "choose_time": "Choose a time", "masters_count": "{count} master{suffix}", "choose_time_master": "Choose a time and then an available master.", "searching_availability": "Searching availability...", "availability_load_error": "Could not load availability.", "time_available_submit": "Time available. You can send the request.", "profile_subtitle": "Update your user, contact and password details.", "username": "Username", "first_name": "First name", "last_name": "Last name", "email": "Email", "phone": "Phone", "save_data": "Save details", "back": "Back", "change_password": "Change password", "change_password_help": "Update your portal password.", "current_password": "Current password", "new_password": "New password", "repeat_password": "Repeat password", "save_password": "Save password",
    },
    "de": {
        "portal_client": "Kundenportal", "site_home": "Website", "logout": "Abmelden", "my_portal": "Mein Portal", "my_data": "Meine Daten", "hello": "Hallo, {name}",
        "portal_subtitle": "Ihre Historie, freigegebene Fotos, Prämien und eine neue Buchungsanfrage.", "my_file": "Meine Kartei", "no_phone": "Keine Telefonnummer", "no_email": "Keine E-Mail", "my_avatar": "Mein Avatar", "update_avatar": "Avatar aktualisieren", "visits": "Besuche", "rewards": "Prämien", "upcoming_bookings": "Kommende Termine", "no_upcoming_bookings": "Sie haben noch keine kommenden Termine.", "rewards_help": "Wählen Sie bei der Buchung eine Prämie. Hier sehen Sie Fortschritt und Rabatt.", "discount": "Rabatt", "need_now": "Benötigt {threshold}; aktuell haben Sie {current}.", "available": "Verfügbar:", "missing": "Fehlen:", "completed": "Abgeschlossen.", "no_rewards": "Keine aktiven Prämien.", "new_booking_request": "Neue Buchungsanfrage", "booking_help": "Wählen Sie Service, Datum, Uhrzeit und Master. Die Anfrage bleibt bis zur Bestätigung offen.", "service": "Service", "date": "Datum", "available_time": "Verfügbare Zeit", "select_service_date": "Service und Datum wählen", "master": "Master", "zone": "Zone", "reward": "Prämie", "comment": "Kommentar", "send_request": "Anfrage senden", "visual_history": "Fotoverlauf", "no_visible_photos": "Noch keine sichtbaren Fotos.", "booking_history": "Buchungsverlauf", "no_bookings": "Sie haben noch keine Buchungen.", "select_master": "Master wählen", "next_short": "nächste {time}", "no_free_time": "keine freie Zeit", "no_free_hours": "Keine freien Zeiten", "no_availability_for_service_date": "Keine verfügbaren Zeiten für diesen Service und dieses Datum.", "choose_time": "Zeit wählen", "masters_count": "{count} Master", "choose_time_master": "Wählen Sie eine Zeit und dann einen verfügbaren Master.", "searching_availability": "Verfügbarkeit wird gesucht...", "availability_load_error": "Verfügbarkeit konnte nicht geladen werden.", "time_available_submit": "Zeit verfügbar. Sie können die Anfrage senden.", "profile_subtitle": "Aktualisieren Sie Benutzer-, Kontakt- und Passwortdaten.", "username": "Benutzername", "first_name": "Vorname", "last_name": "Nachname", "email": "E-Mail", "phone": "Telefon", "save_data": "Daten speichern", "back": "Zurück", "change_password": "Passwort ändern", "change_password_help": "Aktualisieren Sie Ihr Portalpasswort.", "current_password": "Aktuelles Passwort", "new_password": "Neues Passwort", "repeat_password": "Passwort wiederholen", "save_password": "Passwort speichern",
    },
    "fr": {
        "portal_client": "Portail client", "site_home": "Site", "logout": "Sortir", "my_portal": "Mon portail", "my_data": "Mes données", "hello": "Bonjour, {name}",
        "portal_subtitle": "Votre historique, vos photos autorisées, vos récompenses et une nouvelle demande de rendez-vous.", "my_file": "Ma fiche", "no_phone": "Sans téléphone", "no_email": "Sans email", "my_avatar": "Mon avatar", "update_avatar": "Mettre à jour l'avatar", "visits": "Visites", "rewards": "Récompenses", "upcoming_bookings": "Prochains rendez-vous", "no_upcoming_bookings": "Vous n'avez pas encore de prochain rendez-vous.", "rewards_help": "Choisissez une récompense lors de la réservation. Ici vous voyez ce qu'il reste et la remise.", "discount": "Remise", "need_now": "Il faut {threshold}; vous avez maintenant {current}.", "available": "Disponible :", "missing": "Restant :", "completed": "Terminé.", "no_rewards": "Aucune récompense active.", "new_booking_request": "Nouvelle demande de rendez-vous", "booking_help": "Choisissez service, date, heure et master. La demande reste en attente jusqu'à confirmation du salon.", "service": "Service", "date": "Date", "available_time": "Heure disponible", "select_service_date": "Choisissez service et date", "master": "Master", "zone": "Zone", "reward": "Récompense", "comment": "Commentaire", "send_request": "Envoyer la demande", "visual_history": "Historique photo", "no_visible_photos": "Aucune photo visible pour le moment.", "booking_history": "Historique des rendez-vous", "no_bookings": "Vous n'avez pas encore de rendez-vous.", "select_master": "Choisissez un master", "next_short": "proch. {time}", "no_free_time": "aucun horaire libre", "no_free_hours": "Aucun horaire libre", "no_availability_for_service_date": "Aucun horaire disponible pour ce service et cette date.", "choose_time": "Choisissez une heure", "masters_count": "{count} master{suffix}", "choose_time_master": "Choisissez une heure puis un master disponible.", "searching_availability": "Recherche des disponibilités...", "availability_load_error": "Impossible de charger les disponibilités.", "time_available_submit": "Horaire disponible. Vous pouvez envoyer la demande.", "profile_subtitle": "Mettez à jour vos données utilisateur, contact et mot de passe.", "username": "Utilisateur", "first_name": "Prénom", "last_name": "Nom", "email": "Email", "phone": "Téléphone", "save_data": "Enregistrer", "back": "Retour", "change_password": "Changer le mot de passe", "change_password_help": "Mettez à jour votre mot de passe du portail.", "current_password": "Mot de passe actuel", "new_password": "Nouveau mot de passe", "repeat_password": "Répéter le mot de passe", "save_password": "Enregistrer le mot de passe",
    },
}


CLIENT_TRANSLATIONS["es"].update({"login_for_access": "Login de acceso", "edit_login": "Cambiar login", "username_help": "Este usuario se usa para entrar en tu cuenta."})
CLIENT_TRANSLATIONS["ru"].update({"login_for_access": "Логин для входа", "edit_login": "Изменить логин", "username_help": "Этот логин используется для входа в личный кабинет."})
CLIENT_TRANSLATIONS["en"].update({"login_for_access": "Login username", "edit_login": "Change login", "username_help": "This username is used to sign in to your account."})
CLIENT_TRANSLATIONS["de"].update({"login_for_access": "Login-Name", "edit_login": "Login ändern", "username_help": "Dieser Benutzername wird für die Anmeldung verwendet."})
CLIENT_TRANSLATIONS["fr"].update({"login_for_access": "Identifiant de connexion", "edit_login": "Changer l'identifiant", "username_help": "Cet identifiant sert à entrer dans votre compte."})


def normalize_client_language(language):
    code = (language or "").split("-", 1)[0].lower()
    supported = {item[0] for item in CLIENT_LANGUAGES}
    return code if code in supported else DEFAULT_CLIENT_LANGUAGE



def detect_client_language(request):
    explicit = request.session.get(CLIENT_LANGUAGE_SESSION_KEY) or request.COOKIES.get(CLIENT_LANGUAGE_SESSION_KEY)
    if explicit:
        return normalize_client_language(explicit)
    try:
        from core.i18n import PUBLIC_LANGUAGE_SESSION_KEY
    except ImportError:
        PUBLIC_LANGUAGE_SESSION_KEY = "public_language"
    shared = request.session.get(PUBLIC_LANGUAGE_SESSION_KEY) or request.COOKIES.get(PUBLIC_LANGUAGE_SESSION_KEY)
    if shared:
        return normalize_client_language(shared)
    for item in (request.META.get("HTTP_ACCEPT_LANGUAGE") or "").split(","):
        code = item.split(";", 1)[0].strip()
        normalized = normalize_client_language(code)
        if normalized != DEFAULT_CLIENT_LANGUAGE or code.lower().startswith(DEFAULT_CLIENT_LANGUAGE):
            return normalized
    return DEFAULT_CLIENT_LANGUAGE

def translate_client(key, language=None, **kwargs):
    language = normalize_client_language(language)
    text = CLIENT_TRANSLATIONS.get(language, {}).get(key) or CLIENT_TRANSLATIONS[DEFAULT_CLIENT_LANGUAGE].get(key) or key
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, ValueError):
            return text
    return text
