# Generated by Django 6.0.3 on 2026-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='NIE/NIF/CIF'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
    ]
