# Generated by Django 6.0.3 on 2026-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_fiscal_address_client_fiscal_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Notif. Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='notify_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Notif. WhatsApp'),
        ),
    ]
