# Generated by Django 5.2.14 on 2026-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_add_notify_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='acquired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Captado el'),
        ),
        migrations.AddField(
            model_name='client',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de captación'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono alternativo'),
        ),
        migrations.AddField(
            model_name='client',
            name='appointments_frequency',
            field=models.CharField(blank=True, max_length=80, verbose_name='Frecuencia de citas'),
        ),
        migrations.AddField(
            model_name='client',
            name='average_expense_amount_cents',
            field=models.PositiveIntegerField(default=0, verbose_name='Gasto medio (céntimos)'),
        ),
        migrations.AddField(
            model_name='client',
            name='booking_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reservas históricas'),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_notification_marketing',
            field=models.BooleanField(default=False, verbose_name='Consentimiento marketing'),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_notification_services',
            field=models.BooleanField(default=False, verbose_name='Consentimiento avisos de servicio'),
        ),
        migrations.AddField(
            model_name='client',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='client',
            name='external_source',
            field=models.CharField(blank=True, max_length=40, verbose_name='Origen externo'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='client',
            name='how_we_met',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cómo nos conoció'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='Lista negra'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_appointment_at',
            field=models.DateField(blank=True, null=True, verbose_name='Última cita'),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_communications_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marketing aceptado el'),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_communications_accepted_by_venue',
            field=models.BooleanField(default=False, verbose_name='Marketing aceptado en salón'),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_communications_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marketing actualizado el'),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_communications_updated_by_venue',
            field=models.BooleanField(default=False, verbose_name='Marketing actualizado en salón'),
        ),
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='client',
            name='should_receive_marketing_email_notifications',
            field=models.BooleanField(default=False, verbose_name='Marketing por email'),
        ),
        migrations.AddField(
            model_name='client',
            name='should_receive_marketing_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Marketing por SMS'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número IVA'),
        ),
    ]
