PUBLIC_LANGUAGES = [
    ("es", "Español"),
    ("ru", "Русский"),
    ("en", "English"),
    ("de", "Deutsch"),
    ("fr", "Français"),
]

DEFAULT_PUBLIC_LANGUAGE = "es"
PUBLIC_LANGUAGE_SESSION_KEY = "public_language"

PUBLIC_TRANSLATIONS = {
    "es": {
        "site_title": "BRIMOON STUDIO | Belleza premium",
        "home_meta": "BRIMOON Studio en Bilbao: salón de belleza premium especializado en cejas, pestañas, manicura, pedicura y depilación facial con cita previa.",
        "og_home_title": "BRIMOON STUDIO | Belleza premium en Bilbao",
        "og_home_description": "Belleza, cuidado y detalle en cada mirada. Cejas, pestañas, manicura, pedicura y depilación facial.",
        "nav_services": "Servicios", "nav_tips": "Consejos", "nav_gallery": "Galería", "nav_prices": "Precios", "nav_contact": "Contacto", "nav_account": "Mi cuenta", "nav_book": "Reservar cita",
        "kicker_home": "Beauty studio · Bilbao", "hero_title": "BRIMOON STUDIO", "hero_lead": "Belleza, cuidado y detalle en cada mirada", "hero_copy": "Especialistas en cejas, pestañas, manicura, pedicura y depilación facial.", "hero_services": "Ver servicios", "hero_whatsapp": "WhatsApp",
        "trust_1_title": "Atención personalizada", "trust_1_text": "Cada visita se adapta a tu estilo, ritmo y necesidades.", "trust_2_title": "Técnicas profesionales", "trust_2_text": "Protocolos precisos para resultados elegantes y duraderos.", "trust_3_title": "Productos seleccionados", "trust_3_text": "Trabajamos con productos cuidados para piel, manos y mirada.", "trust_4_title": "Ambiente cuidado", "trust_4_text": "Un espacio íntimo para desconectar y sentirte renovada.",
        "services_kicker": "Servicios", "services_title": "Rituales para cuidar cada detalle", "services_text": "Cinco áreas esenciales de belleza con un enfoque delicado, moderno y profesional.", "view_detail": "Ver detalle", "view_service_guide": "Ver guía del servicio",
        "experience_kicker": "Experiencia", "experience_title": "Un espacio pensado para desconectar, cuidarte y salir renovada.", "experience_text": "La estética Brimoon combina calma, precisión y una atención cercana en cada servicio.", "contact_button": "Contactar",
        "guide_kicker": "Guía Brimoon", "guide_title": "Consejos y cuidados para mantener tu resultado", "guide_text": "Un portal útil con ideas sobre cejas, pestañas, manicura y piel para resolver dudas antes y después de tu cita.", "read_tip": "Leer consejo", "view_all_tips": "Ver todos los consejos",
        "prices_kicker": "Precios", "prices_title": "Servicios premium con cita previa", "prices_text": "Consulta disponibilidad y el servicio que mejor encaja contigo desde tu cuenta o por WhatsApp.", "view_treatments": "Ver tratamientos",
        "booking_kicker": "Reserva", "booking_title": "¿Lista para tu momento Brimoon?", "booking_text": "Reserva tu cita y déjanos cuidar cada detalle.", "whatsapp_contact": "Contactar por WhatsApp",
        "account_kicker": "Área cliente", "account_title": "Tu espacio personal", "account_text": "Desde tu cuenta podrás consultar tus citas, revisar servicios reservados y acceder a tus datos de cliente.", "account_access": "Acceder a mi cuenta", "account_create": "Crear cuenta / Solicitar acceso",
        "contact_kicker": "Contacto", "contact_title": "Ven a cuidarte con nosotras", "contact_address": "Dirección: consulta la ubicación exacta al reservar tu cita.", "contact_whatsapp": "WhatsApp: disponible bajo solicitud.", "contact_hours": "Horario: Lunes a sábado con cita previa.", "location": "Ubicación", "footer_text": "Belleza, cuidado y detalle.",
        "home": "Inicio", "service": "Servicio", "all_services_title": "Servicios de belleza en BRIMOON Studio", "all_services_intro": "Explora nuestras áreas de cuidado: mirada, manos, pies y piel facial. Cada servicio está pensado para un resultado elegante, preciso y natural.", "premium_services": "Servicios premium", "tips_cta_kicker": "Consejo Brimoon", "tips_cta_title": "Cuida el resultado también en casa", "tips_cta_text": "Lee nuestros consejos para mantener cejas, pestañas, uñas y piel con mejor aspecto entre citas.", "see_tips": "Ver consejos",
        "what_includes": "Qué incluye este cuidado", "before_after_tips": "Consejos antes y después", "personal_result": "¿Quieres un resultado adaptado a ti?", "also_interest": "También puede interesarte", "more_services": "Más servicios Brimoon",
        "tips_page_title": "Consejos, cuidados y pequeños rituales de belleza", "tips_page_intro": "Un espacio para resolver dudas frecuentes, cuidar mejor los resultados y elegir cada servicio con más criterio.", "useful_portal": "Portal útil", "seo_note_title": "Guías pensadas para tus dudas reales", "seo_note_text": "El portal crecerá con recomendaciones sobre preparación, mantenimiento y elección de servicios para cada necesidad.", "keep_reading": "Sigue leyendo", "more_tips": "Más consejos útiles", "personal_advice": "Reserva tu cita y recibe una recomendación personalizada.",
    },
    "ru": {
        "site_title": "BRIMOON STUDIO | Премиальная красота", "home_meta": "BRIMOON Studio в Бильбао: премиальный салон красоты, брови, ресницы, маникюр, педикюр и депиляция лица по записи.", "og_home_title": "BRIMOON STUDIO | Премиальная красота в Бильбао", "og_home_description": "Красота, уход и внимание к каждой детали.",
        "nav_services": "Услуги", "nav_tips": "Советы", "nav_gallery": "Галерея", "nav_prices": "Цены", "nav_contact": "Контакты", "nav_account": "Мой кабинет", "nav_book": "Записаться",
        "kicker_home": "Beauty studio · Bilbao", "hero_title": "BRIMOON STUDIO", "hero_lead": "Красота, уход и внимание в каждом взгляде", "hero_copy": "Мы специализируемся на бровях, ресницах, маникюре, педикюре и депиляции лица.", "hero_services": "Смотреть услуги", "hero_whatsapp": "WhatsApp",
        "trust_1_title": "Персональный подход", "trust_1_text": "Каждый визит адаптируется под ваш стиль и потребности.", "trust_2_title": "Профессиональные техники", "trust_2_text": "Точные протоколы для элегантного и стойкого результата.", "trust_3_title": "Отобранные продукты", "trust_3_text": "Бережные материалы для кожи, рук и взгляда.", "trust_4_title": "Продуманная атмосфера", "trust_4_text": "Уютное пространство, чтобы расслабиться и обновиться.",
        "services_kicker": "Услуги", "services_title": "Ритуалы ухода в каждой детали", "services_text": "Пять направлений красоты с деликатным и профессиональным подходом.", "view_detail": "Подробнее", "view_service_guide": "Гид по услуге",
        "experience_kicker": "Опыт", "experience_title": "Пространство, где можно отключиться, позаботиться о себе и выйти обновлённой.", "experience_text": "Эстетика Brimoon сочетает спокойствие, точность и внимательное отношение.", "contact_button": "Связаться",
        "guide_kicker": "Гид Brimoon", "guide_title": "Советы и уход, чтобы сохранить результат", "guide_text": "Полезный портал о бровях, ресницах, маникюре и коже до и после визита.", "read_tip": "Читать совет", "view_all_tips": "Все советы",
        "prices_kicker": "Цены", "prices_title": "Премиальные услуги по записи", "prices_text": "Проверьте доступность и подходящую услугу через кабинет или WhatsApp.", "view_treatments": "Смотреть процедуры",
        "booking_kicker": "Запись", "booking_title": "Готовы к своему моменту Brimoon?", "booking_text": "Запишитесь, а мы позаботимся о каждой детали.", "whatsapp_contact": "Написать в WhatsApp",
        "account_kicker": "Кабинет клиента", "account_title": "Ваше личное пространство", "account_text": "В кабинете можно смотреть записи, услуги и свои данные.", "account_access": "Войти в кабинет", "account_create": "Создать доступ", "contact_kicker": "Контакты", "contact_title": "Приходите к нам за уходом", "contact_address": "Адрес: уточняется при записи.", "contact_whatsapp": "WhatsApp: доступен по запросу.", "contact_hours": "График: понедельник-суббота по записи.", "location": "Локация", "footer_text": "Красота, уход и детали.",
        "home": "Главная", "service": "Услуга", "all_services_title": "Услуги красоты в BRIMOON Studio", "all_services_intro": "Изучите направления ухода: взгляд, руки, ноги и кожа лица.", "premium_services": "Премиум услуги", "tips_cta_kicker": "Совет Brimoon", "tips_cta_title": "Ухаживайте за результатом дома", "tips_cta_text": "Читайте советы для бровей, ресниц, ногтей и кожи между визитами.", "see_tips": "Смотреть советы", "what_includes": "Что включает уход", "before_after_tips": "Советы до и после", "personal_result": "Хотите результат под себя?", "also_interest": "Может быть интересно", "more_services": "Другие услуги Brimoon", "tips_page_title": "Советы, уход и маленькие ритуалы красоты", "tips_page_intro": "Здесь мы отвечаем на частые вопросы и помогаем выбирать услуги осознанно.", "useful_portal": "Полезный портал", "seo_note_title": "Гиды под реальные вопросы", "seo_note_text": "Портал будет расти за счёт рекомендаций по подготовке, уходу и выбору услуг.", "keep_reading": "Читайте дальше", "more_tips": "Ещё советы", "personal_advice": "Запишитесь и получите персональную рекомендацию.",
    },
    "en": {
        "site_title": "BRIMOON STUDIO | Premium beauty", "home_meta": "BRIMOON Studio in Bilbao: premium beauty salon for brows, lashes, manicure, pedicure and facial hair removal by appointment.", "og_home_title": "BRIMOON STUDIO | Premium beauty in Bilbao", "og_home_description": "Beauty, care and detail in every look.",
        "nav_services": "Services", "nav_tips": "Tips", "nav_gallery": "Gallery", "nav_prices": "Prices", "nav_contact": "Contact", "nav_account": "My account", "nav_book": "Book appointment", "kicker_home": "Beauty studio · Bilbao", "hero_title": "BRIMOON STUDIO", "hero_lead": "Beauty, care and detail in every look", "hero_copy": "Specialists in brows, lashes, manicure, pedicure and facial hair removal.", "hero_services": "View services", "hero_whatsapp": "WhatsApp",
        "trust_1_title": "Personal care", "trust_1_text": "Every visit adapts to your style, rhythm and needs.", "trust_2_title": "Professional techniques", "trust_2_text": "Precise protocols for elegant and lasting results.", "trust_3_title": "Selected products", "trust_3_text": "Carefully chosen products for skin, hands and eyes.", "trust_4_title": "Curated atmosphere", "trust_4_text": "An intimate space to disconnect and feel renewed.",
        "services_kicker": "Services", "services_title": "Rituals for every detail", "services_text": "Five essential beauty areas with a delicate, modern and professional approach.", "view_detail": "View detail", "view_service_guide": "View service guide", "experience_kicker": "Experience", "experience_title": "A space to disconnect, take care of yourself and leave renewed.", "experience_text": "Brimoon blends calm, precision and warm attention in every service.", "contact_button": "Contact", "guide_kicker": "Brimoon guide", "guide_title": "Tips and care to maintain your result", "guide_text": "A useful portal with ideas about brows, lashes, manicure and skin before and after your appointment.", "read_tip": "Read tip", "view_all_tips": "View all tips",
        "prices_kicker": "Prices", "prices_title": "Premium services by appointment", "prices_text": "Check availability and choose the service that fits you best from your account or WhatsApp.", "view_treatments": "View treatments", "booking_kicker": "Booking", "booking_title": "Ready for your Brimoon moment?", "booking_text": "Book your appointment and let us take care of every detail.", "whatsapp_contact": "Contact by WhatsApp", "account_kicker": "Client area", "account_title": "Your personal space", "account_text": "From your account you can check appointments, reserved services and client details.", "account_access": "Access my account", "account_create": "Create account / request access", "contact_kicker": "Contact", "contact_title": "Come take care of yourself with us", "contact_address": "Address: exact location provided when booking.", "contact_whatsapp": "WhatsApp: available on request.", "contact_hours": "Hours: Monday to Saturday by appointment.", "location": "Location", "footer_text": "Beauty, care and detail.",
        "home": "Home", "service": "Service", "all_services_title": "Beauty services at BRIMOON Studio", "all_services_intro": "Explore care areas for eyes, hands, feet and facial skin.", "premium_services": "Premium services", "tips_cta_kicker": "Brimoon tip", "tips_cta_title": "Care for the result at home", "tips_cta_text": "Read tips to keep brows, lashes, nails and skin looking better between visits.", "see_tips": "View tips", "what_includes": "What this care includes", "before_after_tips": "Before and after tips", "personal_result": "Want a result adapted to you?", "also_interest": "You may also like", "more_services": "More Brimoon services", "tips_page_title": "Beauty tips, care and small rituals", "tips_page_intro": "A space to answer common questions, care for results and choose each service with more confidence.", "useful_portal": "Useful portal", "seo_note_title": "Guides for real questions", "seo_note_text": "The portal will grow with recommendations about preparation, maintenance and service choice.", "keep_reading": "Keep reading", "more_tips": "More useful tips", "personal_advice": "Book your appointment and receive a personalized recommendation.",
    },
}

PUBLIC_TRANSLATIONS["de"] = {**PUBLIC_TRANSLATIONS["en"], **{
    "site_title": "BRIMOON STUDIO | Premium-Beauty", "home_meta": "BRIMOON Studio in Bilbao: Premium-Beauty-Salon für Brauen, Wimpern, Maniküre, Pediküre und Gesichtsdepilation nach Termin.", "og_home_title": "BRIMOON STUDIO | Premium-Beauty in Bilbao", "og_home_description": "Schönheit, Pflege und Liebe zum Detail in jedem Blick.",
    "nav_services": "Services", "nav_tips": "Tipps", "nav_gallery": "Galerie", "nav_prices": "Preise", "nav_contact": "Kontakt", "nav_account": "Mein Konto", "nav_book": "Termin buchen",
    "hero_lead": "Schönheit, Pflege und Detail in jedem Blick", "hero_copy": "Spezialistinnen für Brauen, Wimpern, Maniküre, Pediküre und Gesichtsdepilation.", "hero_services": "Services ansehen",
    "trust_1_title": "Persönliche Betreuung", "trust_1_text": "Jeder Besuch wird an Ihren Stil, Rhythmus und Ihre Bedürfnisse angepasst.", "trust_2_title": "Professionelle Techniken", "trust_2_text": "Präzise Protokolle für elegante und langanhaltende Ergebnisse.", "trust_3_title": "Ausgewählte Produkte", "trust_3_text": "Sorgfältig ausgewählte Produkte für Haut, Hände und Blick.", "trust_4_title": "Gepflegte Atmosphäre", "trust_4_text": "Ein intimer Raum zum Abschalten und Erneuern.",
    "services_kicker": "Services", "services_title": "Rituale für jedes Detail", "services_text": "Fünf zentrale Beauty-Bereiche mit einem sanften, modernen und professionellen Ansatz.", "view_detail": "Details ansehen", "view_service_guide": "Service-Guide ansehen",
    "experience_kicker": "Erlebnis", "experience_title": "Ein Raum zum Abschalten, Pflegen und Erfrischt-Hinausgehen.", "experience_text": "Brimoon verbindet Ruhe, Präzision und herzliche Aufmerksamkeit bei jedem Service.", "contact_button": "Kontakt",
    "guide_kicker": "Brimoon Guide", "guide_title": "Tipps und Pflege, um Ihr Ergebnis zu erhalten", "guide_text": "Ein nützliches Portal mit Ideen zu Brauen, Wimpern, Maniküre und Haut vor und nach dem Termin.", "read_tip": "Tipp lesen", "view_all_tips": "Alle Tipps",
    "prices_kicker": "Preise", "prices_title": "Premium-Services nach Termin", "prices_text": "Prüfen Sie Verfügbarkeit und den passenden Service über Ihr Konto oder WhatsApp.", "view_treatments": "Behandlungen ansehen",
    "booking_kicker": "Buchung", "booking_title": "Bereit für Ihren Brimoon-Moment?", "booking_text": "Buchen Sie Ihren Termin und wir kümmern uns um jedes Detail.", "whatsapp_contact": "Per WhatsApp kontaktieren",
    "account_kicker": "Kundenbereich", "account_title": "Ihr persönlicher Bereich", "account_text": "In Ihrem Konto können Sie Termine, reservierte Services und Kundendaten einsehen.", "account_access": "Mein Konto öffnen", "account_create": "Zugang erstellen / anfragen",
    "contact_kicker": "Kontakt", "contact_title": "Kommen Sie zu uns zur Pflege", "contact_address": "Adresse: genaue Lage bei der Buchung.", "contact_whatsapp": "WhatsApp: auf Anfrage verfügbar.", "contact_hours": "Öffnungszeiten: Montag bis Samstag nach Termin.", "location": "Standort", "footer_text": "Schönheit, Pflege und Detail.",
    "home": "Start", "service": "Service", "all_services_title": "Beauty-Services bei BRIMOON Studio", "all_services_intro": "Entdecken Sie Pflegebereiche für Blick, Hände, Füße und Gesichtshaut.", "premium_services": "Premium-Services", "tips_cta_kicker": "Brimoon Tipp", "tips_cta_title": "Pflegen Sie das Ergebnis auch zu Hause", "tips_cta_text": "Lesen Sie Tipps, damit Brauen, Wimpern, Nägel und Haut zwischen den Terminen besser aussehen.", "see_tips": "Tipps ansehen", "what_includes": "Was diese Pflege umfasst", "before_after_tips": "Tipps davor und danach", "personal_result": "Möchten Sie ein Ergebnis, das zu Ihnen passt?", "also_interest": "Auch interessant", "more_services": "Weitere Brimoon-Services", "tips_page_title": "Beauty-Tipps, Pflege und kleine Rituale", "tips_page_intro": "Ein Bereich für häufige Fragen, bessere Pflege der Ergebnisse und bewusstere Servicewahl.", "useful_portal": "Nützliches Portal", "seo_note_title": "Guides für echte Fragen", "seo_note_text": "Das Portal wächst mit Empfehlungen zu Vorbereitung, Pflege und Servicewahl.", "keep_reading": "Weiterlesen", "more_tips": "Weitere nützliche Tipps", "personal_advice": "Buchen Sie Ihren Termin und erhalten Sie eine persönliche Empfehlung.",
}}
PUBLIC_TRANSLATIONS["fr"] = {**PUBLIC_TRANSLATIONS["en"], **{
    "site_title": "BRIMOON STUDIO | Beauté premium", "home_meta": "BRIMOON Studio à Bilbao : salon de beauté premium pour sourcils, cils, manucure, pédicure et épilation faciale sur rendez-vous.", "og_home_title": "BRIMOON STUDIO | Beauté premium à Bilbao", "og_home_description": "Beauté, soin et détail dans chaque regard.",
    "nav_services": "Services", "nav_tips": "Conseils", "nav_gallery": "Galerie", "nav_prices": "Prix", "nav_contact": "Contact", "nav_account": "Mon compte", "nav_book": "Réserver",
    "hero_lead": "Beauté, soin et détail dans chaque regard", "hero_copy": "Spécialistes des sourcils, cils, manucure, pédicure et épilation faciale.", "hero_services": "Voir les services",
    "trust_1_title": "Attention personnalisée", "trust_1_text": "Chaque visite s'adapte à votre style, votre rythme et vos besoins.", "trust_2_title": "Techniques professionnelles", "trust_2_text": "Protocoles précis pour des résultats élégants et durables.", "trust_3_title": "Produits sélectionnés", "trust_3_text": "Produits choisis avec soin pour la peau, les mains et le regard.", "trust_4_title": "Ambiance soignée", "trust_4_text": "Un espace intime pour déconnecter et ressortir renouvelée.",
    "services_kicker": "Services", "services_title": "Rituels pour chaque détail", "services_text": "Cinq domaines essentiels de beauté avec une approche délicate, moderne et professionnelle.", "view_detail": "Voir le détail", "view_service_guide": "Voir le guide du service",
    "experience_kicker": "Expérience", "experience_title": "Un espace pensé pour déconnecter, prendre soin de vous et repartir renouvelée.", "experience_text": "Brimoon combine calme, précision et attention chaleureuse à chaque service.", "contact_button": "Contacter",
    "guide_kicker": "Guide Brimoon", "guide_title": "Conseils et soins pour garder le résultat", "guide_text": "Un portail utile avec des idées sur les sourcils, cils, manucure et peau avant et après le rendez-vous.", "read_tip": "Lire le conseil", "view_all_tips": "Tous les conseils",
    "prices_kicker": "Prix", "prices_title": "Services premium sur rendez-vous", "prices_text": "Consultez la disponibilité et choisissez le service qui vous convient depuis votre compte ou WhatsApp.", "view_treatments": "Voir les soins",
    "booking_kicker": "Réservation", "booking_title": "Prête pour votre moment Brimoon ?", "booking_text": "Réservez votre rendez-vous et laissez-nous prendre soin de chaque détail.", "whatsapp_contact": "Contacter par WhatsApp",
    "account_kicker": "Espace client", "account_title": "Votre espace personnel", "account_text": "Depuis votre compte, consultez vos rendez-vous, services réservés et données client.", "account_access": "Accéder à mon compte", "account_create": "Créer un compte / demander accès",
    "contact_kicker": "Contact", "contact_title": "Venez prendre soin de vous avec nous", "contact_address": "Adresse : emplacement exact communiqué à la réservation.", "contact_whatsapp": "WhatsApp : disponible sur demande.", "contact_hours": "Horaires : lundi à samedi sur rendez-vous.", "location": "Localisation", "footer_text": "Beauté, soin et détail.",
    "home": "Accueil", "service": "Service", "all_services_title": "Services de beauté chez BRIMOON Studio", "all_services_intro": "Découvrez nos soins pour le regard, les mains, les pieds et la peau du visage.", "premium_services": "Services premium", "tips_cta_kicker": "Conseil Brimoon", "tips_cta_title": "Prenez soin du résultat à la maison", "tips_cta_text": "Lisez nos conseils pour garder sourcils, cils, ongles et peau plus beaux entre les visites.", "see_tips": "Voir les conseils", "what_includes": "Ce que comprend ce soin", "before_after_tips": "Conseils avant et après", "personal_result": "Vous voulez un résultat adapté à vous ?", "also_interest": "Cela peut aussi vous intéresser", "more_services": "Plus de services Brimoon", "tips_page_title": "Conseils beauté, soins et petits rituels", "tips_page_intro": "Un espace pour répondre aux questions fréquentes, mieux entretenir les résultats et choisir chaque service avec plus de confiance.", "useful_portal": "Portail utile", "seo_note_title": "Guides pensés pour vos vraies questions", "seo_note_text": "Le portail grandira avec des recommandations sur la préparation, l'entretien et le choix des services.", "keep_reading": "Continuer à lire", "more_tips": "Plus de conseils utiles", "personal_advice": "Réservez votre rendez-vous et recevez une recommandation personnalisée.",
}}

SERVICE_TRANSLATIONS = {
    "cejas-definicion-depilacion-lifting": {
        "ru": {"title": "Оформление, депиляция и лифтинг бровей", "short": "Дизайн бровей, точная депиляция и лифтинг для выразительного взгляда.", "intro": "Услуга помогает упорядочить, сбалансировать и приподнять выражение лица без потери естественности."},
        "en": {"title": "Brow definition, shaping and lifting", "short": "Brow design, precise hair removal and lifting to enhance your natural expression.", "intro": "A service designed to shape, balance and lift the expression of the face while keeping it natural."},
        "de": {"title": "Brauen-Definition, Depilation und Lifting", "short": "Brauen-Design, präzise Depilation und Lifting für einen ausdrucksvolleren Blick.", "intro": "Ein Service, der die Gesichtsexpression natürlich ordnet und hebt."},
        "fr": {"title": "Définition, épilation et lifting des sourcils", "short": "Design des sourcils, épilation précise et lifting pour sublimer le regard.", "intro": "Un soin pour structurer et relever l'expression du visage tout en gardant un rendu naturel."},
    },
    "depilacion-facial": {"ru": {"title": "Депиляция лица", "short": "Деликатный уход для более чистой и гладкой кожи."}, "en": {"title": "Facial hair removal", "short": "Delicate treatments for cleaner, softer and better cared-for skin."}, "de": {"title": "Gesichtsdepilation", "short": "Sanfte Behandlungen für klarere und weichere Haut."}, "fr": {"title": "Épilation faciale", "short": "Soins délicats pour une peau plus nette, douce et soignée."}},
    "manicura-extensiones-tratamientos": {"ru": {"title": "Маникюр, наращивание и уход", "short": "Элегантный маникюр, наращивание и процедуры для безупречных рук."}, "en": {"title": "Manicure, extensions and treatments", "short": "Elegant manicures, extensions and treatments for impeccable hands."}, "de": {"title": "Maniküre, Extensions und Behandlungen", "short": "Elegante Maniküre und Behandlungen für gepflegte Hände."}, "fr": {"title": "Manucure, extensions et soins", "short": "Manucures élégantes, extensions et soins pour des mains impeccables."}},
    "pedicuras-tratamientos-pies": {"ru": {"title": "Педикюр и уход за стопами", "short": "Комплексный уход для красоты и комфорта ног."}, "en": {"title": "Pedicures and treatments", "short": "Complete foot care, aesthetic pedicure and treatments for wellbeing and beauty."}, "de": {"title": "Pediküre und Behandlungen", "short": "Komplette Fußpflege für Wohlbefinden und Schönheit."}, "fr": {"title": "Pédicures et soins", "short": "Soin complet des pieds, beauté et bien-être."}},
    "pestanas-tinte-extensiones-lifting": {"ru": {"title": "Окрашивание, наращивание и лифтинг ресниц", "short": "Цвет, объём и изгиб для более выразительного взгляда."}, "en": {"title": "Lash tint, extensions and lifting", "short": "Color, volume and curl for a more intense and defined look."}, "de": {"title": "Wimpernfarbe, Extensions und Lifting", "short": "Farbe, Volumen und Schwung für einen definierten Blick."}, "fr": {"title": "Teinture, extensions et lifting de cils", "short": "Couleur, volume et courbure pour un regard plus intense."}},
}

ARTICLE_TRANSLATIONS = {
    "como-cuidar-cejas-despues-lifting": {"ru": {"title": "Как ухаживать за бровями после лифтинга", "summary": "Простые привычки, чтобы сохранить форму и направление бровей."}, "en": {"title": "How to care for your brows after a lift", "summary": "Small habits to preserve shape, shine and direction after brow lifting."}, "de": {"title": "So pflegen Sie Ihre Brauen nach einem Lifting", "summary": "Kleine Gewohnheiten, um Form und Richtung zu bewahren."}, "fr": {"title": "Comment prendre soin des sourcils après un lifting", "summary": "Petites habitudes pour préserver la forme et la direction."}},
    "manicura-elegante-que-dura": {"ru": {"title": "Элегантный маникюр: как продлить стойкость", "summary": "Ежедневный уход и простые привычки для защиты покрытия."}, "en": {"title": "Elegant manicure: habits to make it last", "summary": "Daily care, cuticle oil and simple gestures to protect the finish."}, "de": {"title": "Elegante Maniküre: So hält sie länger", "summary": "Tägliche Pflege und einfache Gesten zum Schutz des Finishs."}, "fr": {"title": "Manucure élégante : habitudes pour la faire durer", "summary": "Soins quotidiens et gestes simples pour protéger la finition."}},
    "depilacion-facial-piel-sensible": {"ru": {"title": "Депиляция лица и чувствительная кожа", "summary": "Подготовка и уход после процедуры, чтобы коже было комфортнее."}, "en": {"title": "Facial hair removal and sensitive skin", "summary": "Preparation and aftercare for calmer-feeling skin."}},
    "mirada-natural-pestanas-cejas": {"ru": {"title": "Естественный взгляд: брови и ресницы без перегруза", "summary": "Идеи для деликатного и утончённого акцента на взгляде."}, "en": {"title": "Natural look: combining brows and lashes", "summary": "Ideas to enhance your eyes while keeping a refined natural finish."}},
}


def normalize_public_language(language):
    code = (language or "").split(",", 1)[0].split(";", 1)[0].split("-", 1)[0].lower()
    supported = {item[0] for item in PUBLIC_LANGUAGES}
    return code if code in supported else DEFAULT_PUBLIC_LANGUAGE


def detect_public_language(request):
    explicit = request.session.get(PUBLIC_LANGUAGE_SESSION_KEY) or request.COOKIES.get(PUBLIC_LANGUAGE_SESSION_KEY)
    if explicit:
        return normalize_public_language(explicit)
    for item in (request.META.get("HTTP_ACCEPT_LANGUAGE") or "").split(","):
        lang = normalize_public_language(item)
        if lang != DEFAULT_PUBLIC_LANGUAGE or item.lower().startswith(DEFAULT_PUBLIC_LANGUAGE):
            return lang
    return DEFAULT_PUBLIC_LANGUAGE


def public_texts(language):
    language = normalize_public_language(language)
    return {**PUBLIC_TRANSLATIONS[DEFAULT_PUBLIC_LANGUAGE], **PUBLIC_TRANSLATIONS.get(language, {})}


def localize_items(items, translations, language):
    language = normalize_public_language(language)
    localized = []
    for item in items:
        data = {**item}
        data.update(translations.get(item["slug"], {}).get(language, {}))
        if language in ("de", "fr") and not translations.get(item["slug"], {}).get(language):
            data.update(translations.get(item["slug"], {}).get("en", {}))
        localized.append(data)
    return localized
