from django.urls import path
from .views import (
    booking_list,
    booking_create,
    booking_update,
    booking_delete,
    service_data_api,
    client_reward_api,
    booking_slot_check_api,
    booking_availability,
    booking_calendar_day,
    calendar_time_block_create_api,
    calendar_time_block_update_api,
    calendar_time_block_delete_api,
    calendar_break_update_api,
    booking_reschedule_api,
    booking_status_api,
    booking_quick_status_update,
    booking_photo_image,
    booking_photo_delete,
    booking_photos_partial,
    booking_photo_upload_api,
    booking_photo_delete_api,
)

app_name = "bookings"

urlpatterns = [
    path("", booking_list, name="list"),
    path("new/", booking_create, name="create"),
    path("calendar/", booking_calendar_day, name="calendar_day"),
    path("availability/", booking_availability, name="availability"),
    path("api/service-data/", service_data_api, name="service_data_api"),
    path("api/client-reward/", client_reward_api, name="client_reward_api"),
    path("api/time-blocks/", calendar_time_block_create_api, name="time_block_create_api"),
    path("api/time-blocks/<int:pk>/update/", calendar_time_block_update_api, name="time_block_update_api"),
    path("api/time-blocks/<int:pk>/delete/", calendar_time_block_delete_api, name="time_block_delete_api"),
    path("api/breaks/update/", calendar_break_update_api, name="break_update_api"),
    path("api/<int:pk>/reschedule/", booking_reschedule_api, name="reschedule_api"),
    path("api/<int:pk>/status/", booking_status_api, name="status_api"),
    path("api/<int:pk>/photos/", booking_photos_partial, name="photos_partial_api"),
    path("api/<int:pk>/photos/upload/", booking_photo_upload_api, name="photo_upload_api"),
    path("api/<int:booking_pk>/photos/<int:photo_pk>/delete/", booking_photo_delete_api, name="photo_delete_api"),
    path("<int:pk>/quick-status/", booking_quick_status_update, name="quick_status"),
    path("photos/<int:pk>/image/", booking_photo_image, name="photo_image"),
    path("<int:booking_pk>/photos/<int:photo_pk>/delete/", booking_photo_delete, name="photo_delete"),
    path("<int:pk>/edit/", booking_update, name="update"),
    path("api/slot-check/", booking_slot_check_api, name="slot_check_api"),
    path("<int:pk>/delete/", booking_delete, name="delete"),
]
