# Generated by Django 6.0.3 on 2026-04-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allowed_zones',
            field=models.ManyToManyField(blank=True, related_name='services', to='salon.zone', verbose_name='Zonas permitidas'),
        ),
    ]
