# Generated by Django 6.0.3 on 2026-04-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_service_allowed_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
