# Generated by Django 6.0.3 on 2026-04-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_remove_service_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
