# Generated by Django 6.0.3 on 2026-07-07 14:51

from django.db import migrations, models


def set_service_categories(apps, schema_editor):
    Service = apps.get_model("services_app", "Service")

    for service in Service.objects.all():
        name = (service.name or "").lower()
        if "cejas" in name:
            category = "brows"
        elif "pesta" in name:
            category = "lashes"
        elif "pedic" in name or "pies" in name:
            category = "pedicure"
        elif "manic" in name or "uña" in name or "unas" in name:
            category = "manicure"
        elif "depil" in name:
            category = "depilation"
        else:
            category = "other"
        service.category = category
        service.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_service_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('brows', 'Cejas'), ('lashes', 'Pestañas'), ('manicure', 'Manicura'), ('pedicure', 'Pedicura'), ('depilation', 'Depilación'), ('facial', 'Facial'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría'),
        ),
        migrations.RunPython(set_service_categories, migrations.RunPython.noop),
    ]
