# Generated by Django 6.0.3 on 2026-06-20 10:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_payment_entry_type_cashclosure'),
        ('services_app', '0005_service_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Cantidad')),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fiscal_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.fiscaldocument', verbose_name='Documento')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_document_lines', to='services_app.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Línea de documento',
                'verbose_name_plural': 'Líneas de documento',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
