# Generated by Django 6.0.3 on 2026-07-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatwellReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatwell_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('reviewer_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('employee', models.CharField(blank=True, max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['-date'], name='reviews_tre_date_cfba9c_idx'), models.Index(fields=['rating'], name='reviews_tre_rating_1b54ce_idx')],
            },
        ),
    ]
