# Generated by Django 6.0.3 on 2026-07-08 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_bookingprepayment_bookingwaitlistentry'),
        ('clients', '0006_client_fiscal_address_client_fiscal_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=120, unique=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_pending', 'QR pending'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('bridge_session_id', models.CharField(blank=True, max_length=120)),
                ('last_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLoginLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_links', to='whatsapp_bot.whatsappconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('reminder_24h', 'Reminder 24h'), ('reminder_2h', 'Reminder 2h'), ('manual', 'Manual')], max_length=40)),
                ('to_phone', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=180)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='bookings.booking')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='clients.client')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='whatsapp_bot.whatsappconnection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'kind'), name='unique_whatsapp_booking_message_kind')],
            },
        ),
    ]
