# Generated by Django 6.0.3 on 2026-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('reminder_24h', 'Reminder 24h'), ('reminder_2h', 'Reminder 2h'), ('welcome_credentials', 'Welcome / login credentials'), ('payment_receipt', 'Payment receipt'), ('birthday_greeting', 'Birthday greeting'), ('manual', 'Manual')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='kind',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('reminder_24h', 'Reminder 24h'), ('reminder_2h', 'Reminder 2h'), ('welcome_credentials', 'Welcome / login credentials'), ('payment_receipt', 'Payment receipt'), ('birthday_greeting', 'Birthday greeting'), ('manual', 'Manual')], max_length=40),
        ),
    ]
