# Generated by Django 5.2.14 on 2026-07-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_client_responded_at_booking_client_response'),
        ('clients', '0007_add_notify_preferences'),
        ('whatsapp_bot', '0003_waitlist_message_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='waitlist_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='bookings.bookingwaitlistentry'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessage',
            constraint=models.UniqueConstraint(fields=('waitlist_entry', 'kind'), name='unique_whatsapp_waitlist_message_kind'),
        ),
    ]
