# Generated by Django 5.2.14 on 2026-07-24 19:59

from django.db import migrations, models


def update_action_and_review_templates(apps, schema_editor):
    template_model = apps.get_model("whatsapp_bot", "WhatsAppTemplate")
    reminder, _created = template_model.objects.get_or_create(
        kind="reminder_24h",
        defaults={
            "name": "Recordatorio 24h antes",
            "body": (
                "Hola {client_name}. Te recordamos tu cita en {salon_name} manana "
                "{date} a las {time} para {service_name}."
            ),
        },
    )
    if "{attend_url}" not in reminder.body or "{decline_url}" not in reminder.body:
        reminder.body = (
            reminder.body.rstrip()
            + "\n\nConfirma tu asistencia:\n"
            + "Voy: {attend_url}\n"
            + "No voy: {decline_url}"
        )
        reminder.save(update_fields=["body", "updated_at"])

    template_model.objects.get_or_create(
        kind="review_request",
        defaults={
            "name": "Solicitud de resena despues de la cita",
            "body": (
                "Hola {client_name}. Gracias por visitarnos en {salon_name}.\n\n"
                "Nos ayudas mucho dejando tu opinion sobre {service_name}:\n"
                "Opinion privada en tu area personal: {review_url}\n"
                "Resena en Google: {google_review_url}"
            ),
            "enabled": True,
            "delay_minutes": 120,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_whatsappmessage_waitlist_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='kind',
            field=models.CharField(choices=[('waitlist_joined', 'Waitlist joined'), ('waitlist_slot_available', 'Waitlist slot available'), ('booking_confirmation', 'Booking confirmation'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('reminder_24h', 'Reminder 24h'), ('reminder_2h', 'Reminder 2h'), ('welcome_credentials', 'Welcome / login credentials'), ('payment_receipt', 'Payment receipt'), ('birthday_greeting', 'Birthday greeting'), ('review_request', 'Review request'), ('manual', 'Manual')], max_length=40),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='kind',
            field=models.CharField(choices=[('waitlist_joined', 'Waitlist joined'), ('waitlist_slot_available', 'Waitlist slot available'), ('booking_confirmation', 'Booking confirmation'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('reminder_24h', 'Reminder 24h'), ('reminder_2h', 'Reminder 2h'), ('welcome_credentials', 'Welcome / login credentials'), ('payment_receipt', 'Payment receipt'), ('birthday_greeting', 'Birthday greeting'), ('review_request', 'Review request'), ('manual', 'Manual')], max_length=40, unique=True),
        ),
        migrations.RunPython(
            update_action_and_review_templates,
            migrations.RunPython.noop,
        ),
    ]
