# Generated by Django 6.0.3 on 2026-04-03 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('salon', '0001_initial'),
        ('services_app', '0002_service_allowed_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Inicio')),
                ('end_at', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('done', 'Hecha'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio guardado')),
                ('duration_snapshot', models.PositiveIntegerField(default=60, verbose_name='Duración guardada (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clients.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='employees.employee', verbose_name='Empleado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services_app.service', verbose_name='Servicio')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='salon.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_at'],
            },
        ),
    ]
