# Generated by Django 6.0.3 on 2026-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='employee_amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe empleado'),
        ),
        migrations.AddField(
            model_name='booking',
            name='employee_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje empleado'),
        ),
        migrations.AddField(
            model_name='booking',
            name='salon_amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe salón'),
        ),
    ]
