# Generated by Django 6.0.3 on 2026-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_client_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_client_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio original cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_reward_applied',
            field=models.BooleanField(default=False, verbose_name='Premio aplicado'),
        ),
    ]
