# Generated by Django 6.0.3 on 2026-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('website', 'Sitio web'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('phone', 'Teléfono'), ('walk_in', 'En el salón'), ('rebooking', 'Cliente recurrente'), ('referral', 'Recomendación'), ('google', 'Google / Maps'), ('other', 'Otro')], default='manual', max_length=20, verbose_name='Origen'),
        ),
    ]
