# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("website", "Sitio web"),
                    ("whatsapp", "WhatsApp"),
                    ("instagram", "Instagram"),
                    ("phone", "Teléfono"),
                    ("walk_in", "En el salón"),
                    ("rebooking", "Cliente recurrente"),
                    ("referral", "Recomendación"),
                    ("employee", "Empleado"),
                    ("google", "Google / Maps"),
                    ("other", "Otro"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
    ]
