# Generated by Django 6.0.3 on 2026-05-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_reward_rule'),
        ('clients', '0005_client_rewards'),
        ('employees', '0008_employeerecurringtimeblock'),
        ('payments', '0001_initial'),
        ('services_app', '0005_service_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPrepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe de prepago')),
                ('status', models.CharField(choices=[('paid', 'Pagada'), ('refunded', 'Devuelta'), ('forfeited', 'Para salon')], default='paid', max_length=20, verbose_name='Estado')),
                ('refundable_until', models.DateTimeField(verbose_name='Devolucion disponible hasta')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Devuelto el')),
                ('forfeited_at', models.DateTimeField(blank=True, null=True, verbose_name='Asignado al salon el')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment', to='bookings.booking', verbose_name='Reserva')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_prepayment', to='payments.payment', verbose_name='Pago online')),
            ],
            options={
                'verbose_name': 'Prepago de reserva',
                'verbose_name_plural': 'Prepagos de reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateField(verbose_name='Fecha deseada')),
                ('time_range', models.CharField(blank=True, max_length=20, verbose_name='Rango horario')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('notified', 'Notificada'), ('booked', 'Convertida en reserva'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(default='website', max_length=20, verbose_name='Origen')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='clients.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='employees.employee', verbose_name='Empleado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='services_app.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Entrada en lista de espera',
                'verbose_name_plural': 'Lista de espera',
                'ordering': ['desired_date', 'created_at'],
            },
        ),
    ]
