# Generated by Django 5.2.14 on 2026-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_bookingprepayment_bookingwaitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido el'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_response',
            field=models.CharField(choices=[('pending', 'Sin respuesta'), ('attending', 'Asistira'), ('declined', 'No asistira')], default='pending', max_length=20, verbose_name='Respuesta del cliente'),
        ),
    ]
