# Generated by Django 5.2.14 on 2026-07-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_client_responded_at_booking_client_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizada el'),
        ),
    ]
