# Generated by Django 6.0.3 on 2026-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_bookingwaitlistentry_desired_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Agrupa varias reservas creadas juntas (ej. multiples servicios en una misma sesion).', null=True, verbose_name='ID de grupo'),
        ),
    ]
