from django.urls import path

from . import views


app_name = "mobile_api"

urlpatterns = [
    path("app-update/", views.AppUpdateView.as_view(), name="app_update"),
    path("password-recovery/", views.PasswordRecoveryView.as_view(), name="password_recovery"),
    path("me/", views.MeView.as_view(), name="me"),
    path("push-devices/", views.PushDeviceView.as_view(), name="push_devices"),
    path("whatsapp/status/", views.WhatsAppStatusView.as_view(), name="whatsapp_status"),
    path("clients/", views.ClientListView.as_view(), name="clients"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/avatar/", views.ClientAvatarView.as_view(), name="client_avatar"),
    path("clients/<int:pk>/rewards/", views.ClientRewardProgressView.as_view(), name="client_rewards"),
    path("client-reward-rules/", views.ClientRewardRuleListView.as_view(), name="client_reward_rules"),
    path("client-reward-rules/<int:pk>/", views.ClientRewardRuleDetailView.as_view(), name="client_reward_rule_detail"),
    path("employees/", views.EmployeeListView.as_view(), name="employees"),
    path("employees/<int:pk>/", views.EmployeeDetailView.as_view(), name="employee_detail"),
    path("employees/<int:pk>/schedule/", views.EmployeeScheduleView.as_view(), name="employee_schedule"),
    path("employees/<int:pk>/schedule/vacation/", views.EmployeeVacationDayView.as_view(), name="employee_vacation_day"),
    path("employees/<int:pk>/schedule/break/", views.EmployeeBreakView.as_view(), name="employee_break"),
    path("employees/<int:pk>/schedule/extend-slot/", views.EmployeeScheduleSlotExtendView.as_view(), name="employee_schedule_extend_slot"),
    path("services/", views.ServiceListView.as_view(), name="services"),
    path("services/<int:pk>/", views.ServiceDetailView.as_view(), name="service_detail"),
    path("zones/", views.ZoneListView.as_view(), name="zones"),
    path("zones/<int:pk>/", views.ZoneDetailView.as_view(), name="zone_detail"),
    path("bookings/", views.BookingListCreateView.as_view(), name="bookings"),
    path("bookings/check-availability/", views.BookingAvailabilityCheckView.as_view(), name="booking_check_availability"),
    path("availability/slots/", views.AvailabilitySlotsView.as_view(), name="availability_slots"),
    path("bookings/<int:pk>/", views.BookingDetailView.as_view(), name="booking_detail"),
    path("bookings/<int:pk>/prepayment/", views.BookingPrepaymentView.as_view(), name="booking_prepayment"),
    path("bookings/<int:pk>/payment/", views.BookingPaymentStartView.as_view(), name="booking_payment"),
    path("bookings/<int:pk>/stripe-checkout/", views.BookingStripeCheckoutView.as_view(), name="booking_stripe_checkout"),
    path("bookings/<int:pk>/cancel/", views.BookingCancelView.as_view(), name="booking_cancel"),
    path("bookings/<int:pk>/client-reschedule/", views.BookingClientRescheduleView.as_view(), name="booking_client_reschedule"),
    path("bookings/<int:pk>/edit-services/", views.BookingEditServicesView.as_view(), name="booking_edit_services"),
    path("bookings/<int:pk>/quick-payment/", views.BookingQuickPaymentView.as_view(), name="booking_quick_payment"),
    path("bookings/<int:pk>/cash-document/", views.BookingCashDocumentView.as_view(), name="booking_cash_document"),
    path("bookings/<int:pk>/photos/", views.BookingPhotoListCreateView.as_view(), name="booking_photos"),
    path("bookings/<int:pk>/reschedule/", views.BookingRescheduleView.as_view(), name="booking_reschedule"),
    path("bookings/<int:pk>/status/", views.BookingStatusView.as_view(), name="booking_status"),
    path("photos/<int:pk>/", views.BookingPhotoDetailView.as_view(), name="booking_photo_detail"),
    path("photos/<int:pk>/image/", views.BookingPhotoImageView.as_view(), name="booking_photo_image"),
    path("time-blocks/", views.TimeBlockListCreateView.as_view(), name="time_blocks"),
    path("time-blocks/<str:pk>/", views.TimeBlockDetailView.as_view(), name="time_block_detail"),
    path("calendar/day/", views.CalendarDayView.as_view(), name="calendar_day"),
    path("cashbox/", views.CashboxSummaryView.as_view(), name="cashbox"),
    path("deposit-settings/", views.DepositSettingsView.as_view(), name="deposit_settings"),
    path("cashbox/stripe/payout/", views.StripePayoutView.as_view(), name="stripe_payout"),
    path("cashbox/receipt-template/", views.ReceiptTemplateView.as_view(), name="receipt_template"),
    path("cashbox/receipt-template/reset/", views.ReceiptTemplateResetView.as_view(), name="receipt_template_reset"),
    path("cashbox/close/", views.CashboxCloseView.as_view(), name="cashbox_close"),
    path("cashbox/documents/<int:pk>/", views.CashDocumentDetailView.as_view(), name="cash_document_detail"),
    path("cashbox/documents/<int:pk>/lines/", views.CashDocumentLineCreateView.as_view(), name="cash_document_line_create"),
    path("cashbox/lines/<int:pk>/", views.CashDocumentLineDetailView.as_view(), name="cash_document_line_detail"),
    path("cashbox/documents/<int:pk>/payments/", views.CashDocumentPaymentCreateView.as_view(), name="cash_document_payment_create"),
    path("cashbox/payments/<int:pk>/", views.CashPaymentDetailView.as_view(), name="cash_payment_detail"),
    path("cashbox/documents/<int:pk>/share/", views.CashDocumentShareView.as_view(), name="cash_document_share"),
    path("notifications/", views.NotificationTemplateListView.as_view(), name="notification_templates"),
    path("notifications/<str:kind>/", views.NotificationTemplateDetailView.as_view(), name="notification_template_detail"),
    path("notifications/<str:kind>/reset/", views.NotificationTemplateResetView.as_view(), name="notification_template_reset"),
    path('waitlist/', views.WaitlistEntryListView.as_view(), name='waitlist'),
    path('waitlist/<int:pk>/', views.WaitlistEntryDetailView.as_view(), name='waitlist_detail'),
]
